namespace TeamTimeWarp.Domain.Entities
{
    public enum AccountType
    {
        //autogenerated.
        Fake,
        //email, username, and password
        Full,
        //quick login: only user name, 
        Quick
    }

    public class LazyAccount : Account
    {
        public LazyAccount(long id)
        {
            Id = id;
        }
    }

    public class Account
    {
        public virtual long Id { get; protected set; }
        public virtual string Name { get; protected set; }
        public virtual string Email { get; protected set; }
        public virtual AccountType AccountType { get; protected set; }

        public Account(long id, string name, string emailAddress, AccountType accountType)
        {
            Id = id;
            Name = name;
            Email = emailAddress;
            AccountType = accountType;
        }

        protected Account()
        {
            
        }
    }
}
